# permissions for end users to view postgresstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: postgress-gorm-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresstore-viewer-role
rules:
- apiGroups:
  - postgressgroup.venkateshredhat.com
  resources:
  - postgresstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgressgroup.venkateshredhat.com
  resources:
  - postgresstores/status
  verbs:
  - get
