# permissions for end users to edit postgresstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: postgress-gorm-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresstore-editor-role
rules:
- apiGroups:
  - postgressgroup.venkateshredhat.com
  resources:
  - postgresstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgressgroup.venkateshredhat.com
  resources:
  - postgresstores/status
  verbs:
  - get
